apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-video-srt-app
  labels:
    app: my-video-srt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-video-srt-app
  template:
    metadata:
      labels:
        app: my-video-srt-app
    spec:
      containers:
      - name: my-video-srt-app
        image: luminoussg/my-video-srt-app:v1.2
        ports:
        - containerPort: 8080  # For possible web UI
          name: web
        - containerPort: 1935  # Common SRT port
          name: srt-tcp
          protocol: TCP
        - containerPort: 1935  # Common SRT port (UDP)
          name: srt-udp
          protocol: UDP
        - containerPort: 4200  # Alternative SRT port 
          name: srt-alt
          protocol: UDP
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-video-srt-app
spec:
  selector:
    app: my-video-srt-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    name: web
  - port: 1935
    targetPort: 1935
    protocol: TCP
    nodePort: 31935
    name: srt-tcp
  - port: 1935
    targetPort: 1935
    protocol: UDP 
    nodePort: 31935
    name: srt-udp
  - port: 4200
    targetPort: 4200
    protocol: UDP
    nodePort: 34200
    name: srt-alt
  type: NodePort 