apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - my-video-srt-app-deployment.yaml
  - my-video-srt-app-svc.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: my-video-srt-app
  app.kubernetes.io/instance: my-video-srt-app

images:
  - name: luminoussg/my-video-srt-app
    newTag: v1.2 