apiVersion: v1
kind: Service
metadata:
  name: my-video-srt-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: srt-tcp
  - port: 1935
    targetPort: 1935
    protocol: UDP
    name: srt-udp
  - port: 4200
    targetPort: 4200
    protocol: UDP
    name: srt-alt
  selector:
    app: my-video-srt-app
  type: NodePort 